sudo: false
language: rust

# necessary for `travis-cargo coveralls --no-sudo`
#addons:
#  apt:
#    packages:
#      - libcurl4-openssl-dev
#      - libelf-dev
#      - libdw-dev
#      - binutils-dev # optional: only required for the --verify flag of coveralls

rust:
  - stable
  - nightly

before_script:
  # load travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test
  #- travis-cargo bench
  - travis-cargo --only stable doc

after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  - travis-cargo --only stable doc-upload
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  #- travis-cargo coveralls --no-sudo --verify

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    #- TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - secure: "aWS8QQ41R6GpSkM56UzFWsI1QBzun1PatvW6OhQgojQY3yd6fk4DPJz6yuVcb56PpNPwJNfKZNIFLgB0d6a1ej/wAHisVHW+1aZfI2P9edFejMHU5nNqw2bz8t6H0+aEqIxv2aT35Q0PeLFgWj4bMTXixm8L1PfiKF4X3VQqtjQljagSIE9GI5k4Zg9N1GYEsTzAVvZADIkRXkbIuGWC474K8qD5MN0u9bPfGHiV22/Az1wgPMs27716vju4LCTf4zcdtIJY0IEBcPaV5BQuJ7KmUZ5Hcd8VQBYFkaKCgvsvLAN7+NS686LpKPNtG1WoPFSzeNn1a2XpcR/xXI+GZ82AMtO2hJsJCJbBzEGo3JPCeqN26SlNHrYipRiw2a7OywcPclIdyq4FJkp9E/A6NXbXP/em8d/IdCFELm8PlPAQ2IygwT6mrbkxUJGYT7ylvYcCCvL93qDl6mFHzSu0p2fQFTRlD7XYbeV2wm51mshxS3KGRgF0xXk3XT+YtCoc4LxelXZh3tY8OXWh/nbRopqRGyY70oxwg3Isv7CZPMsHoeZ78ofU4Sr2cVo2Zx8G0MLR2hOBG+UhGEU5jQyPodWQO/0EutqCLtlM7RyUS4Oth2Jtx1+gfFaIj68grXIcNedHV0YBGHYOxqGywY0b+9mhRcDo2IIdEdbLm6L6DqI="